-- The schema now lives in numbered migrations under app/migrations/.
-- Apply with:  python -m app.migrate
--
-- 001_baseline.sql contains this file's original contents (all IF NOT EXISTS),
-- so running the migrator against an existing database is a safe no-op.
